# Generated by Django 3.0.6 on 2020-06-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
                ('price', models.CharField(max_length=225)),
                ('promotion', models.CharField(max_length=255)),
                ('foc', models.CharField(max_length=255)),
                ('exp', models.DateTimeField()),
                ('start', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
